### ISSUE TITLE
Linux ever?

### ISSUE THREAD

**Issue by LuciousLisa** [topeterk/HitCounterManager#8]
I love how this project looks and would love to use it at some point! Any chance at all there will ever be a Linux compatible version for it? :)

**Comment by topeterk** [comment]
Hi, I was already asked, if this would become available for MAC. Since I don't use Linux at all as a Desktop OS and don't own any iOS copy, I think there will be no Linux or MAC compatible version built by myself in the near future, sorry.

**However if someone is reading this and wants to help me out in porting the software to another OS, please have a look at Shortcuts.cs as it should be the only file that needs to be modified in order to support other platforms.**

**Comment by topeterk** [comment]
Even the mono project doesn't seem to have good support for global system hot keys. Also searched a while for a C# linux implementation for hot keys but couldn't find any good one that I can make use of.

Most promising to me is [Global Hotkey in Mono and Gtk#](https://stackoverflow.com/questions/2349958/global-hotkey-in-mono-and-gtk#) but even that sounds like "it may work o.O" rather than "it works, always!"

PS: The HitCounterManager without any hot key functionality should also work on other platforms as it is plain dotNet code when there is a dotNet framework available for the OS. That means one has to remove all external WinAPI calls of Shortcuts.cs and insert some sort of stub or empty function.

**Comment by evitalis** [comment]
While I think the hotkeys are helpful, if they had to be added to a Linux port later my opinion is that would be acceptable. It isn't that big of a deal to Alt+Tab to click the button if needed.

**Comment by topeterk** [comment]
I removed the WindowsAPI calls and inserted stubs to run the application using Mono on Ubuntu 18.04. Unluckily it crashes and will not startup successfully but at least it started - until the crash happend :)
Finding the solution may cost some time as the exceptions should not occur and there is no reason for that. It works with Microsoft .Net Framework and I have to workaround the issues that Mono is seeing.

**Comment by topeterk** [comment]
I updated the source that works with Mono quite well today. Only issue I can see so far (_no final deep testing done yet_) is that the session progress (_right side checkbox of the splits_) is not updated correctly.
Also I had to disabled global hotkeys in the application, so maybe someone finds a solution to get it working for Linux or MAC and can help me out with an implementation. I'm sorry but I guess I will not dig deeper into global hotkeys for other OSes.
However, as it looks good so far, I am planning to upload also a release package that can be run with Mono on upcoming releases.
Just need some final testing (_also for the Windows version as I switched from VB to C#_) and updating of documentation (_Readme/Wiki_).

**Comment by topeterk** [comment]
OK guys, you may want to have a look at the [version 1.14](https://github.com/topeterk/HitCounterManager/releases/tag/1.14.0.0) that I just released.
This version comes with a Mono compatible executable.
Hopefully it works on your end although the global hot keys will not work, unfortunately.

I appreciate any feedback if this version is fine so far or if there is anything we can do better next time, so   I will keep this issue open for now.

**Comment by LuciousLisa** [comment]
Thanks for the work so far! I'll try it out soon and let you know about my experiences.

**Comment by LuciousLisa** [comment]
I'm going to list my findings here. I'm not super savvy, but I'll try to be meticulous to make up for that. :smiley:   

Path to my HCM folder: /home/lisa/.local/opt/HitCounterManager

1. Can't load profiles:
- [Screenshot of intended use (from your video)](https://i.imgur.com/evMhE3O.png).
- [Screenshot of my application](https://i.imgur.com/n8Afu82.png).
2. Cursor gets stuck in text field for hits/pb when editing the number:
- [Short video demonstrating this issue](https://youtu.be/gCj11yc-2dE). Note that the video only shows the hits field, but this behaviour is identical when done with the pb field.
3. [HitCounterManagerSave.xml](https://i.imgur.com/Sv7xjxE.png) is written to (and read from) the home folder instead of the application's folder (which would be the desired result). Steps to replicate:
- Open application.
- Click icon to create new profile.
- Name profile in dialogue window, click OK to confirm.
- Result: HitCounter.html is created in /home.
- Click icon to save session.
- Result: two new files are created in /home (HitCounterManagerSave.xml)

Let me know if you'd like me to open separate issues for each (or some) of them and if so, what additional info you need. I chose not to, to keep from overwhelming the repo (and potentially you) with multiple issues. :wink:

**Comment by topeterk** [comment]
Good idea to add some kind of launcher script. I'll have a look at this and add it to the next version.

**Comment by topeterk** [comment]
I'm closing this issue at this point. Thanks for the support 👍
